window.GREENECO = {
  company: {
    name: "ООО «ГРИН ЭКО»",
    fullName: "Общество с ограниченной ответственностью «ГРИН ЭКО»",
    brand: "ГРИН ЭКО",
    slogan: "Овощи и фрукты с собственных полей — оптом, без посредников",
    inn: "2348042571",
    kpp: "773401001",
    ogrn: "1212300006049",
    okpo: "47145444",
    legalAddress: "123182, город Москва, Волоколамское ш., д. 24 к. 1, помещ. 699",
    warehouse: "123182, город Москва, Волоколамское ш., д. 24 к. 1, помещ. 699",
    bank: "ФИЛИАЛ «РОСТОВСКИЙ» АО «АЛЬФА-БАНК»",
    rs: "40702810926210002713",
    ks: "30101810500000000207",
    bik: "046015207",
    director: "Татьяна Михайловна Суханова",
    phoneSales: "+7 (928) 122-13-55",
    phoneSalesHref: "tel:+79281221355",
    phoneAcc: "+7 (928) 122-13-55",
    phoneAccHref: "tel:+79281221355",
    whatsapp: "https://wa.me/79281221355",
    telegram: "https://wa.me/79281221355",
    email: "grineko.ooo@mail.ru",
    emailSales: "grineko.ooo@mail.ru",
    email2: "kompaniagrineko@yandex.ru",
    hours: "Пн–Сб: 8:00–18:00",
    priceUpdated: "01.10.2026",
    hectares: "1 240",
    tons: "28 000",
    years: "14",
    greenhouses: "18 га",
  },
  products: [
    {
      id: "tomaty",
      name: "Томаты",
      category: "ovoshchi",
      categoryName: "Овощи",
      url: "produkciya/ovoshchi/tomaty.html",
      seo: "купить томаты оптом",
      variety: "Розовый мёд, Пинк Парадайз, сливовидные",
      caliber: "40–70 мм / 70–90 мм",
      pack: "пластиковый лоток 6 кг, гофрокороб 10 кг",
      storage: "+8…+12 °C, влажность 85–90%",
      shelf: "10–14 суток",
      season: "май–октябрь (грунт), круглый год (теплица)",
      seasonKeys: ["leto", "vesna", "osen", "zima"],
      packKeys: ["lotok", "gofra"],
      caliberKeys: ["sredniy", "krupnyy"],
      volume: "до 80 т/нед",
      priceKg: 89,
      pricePack: 890,
      priceTon: 82000,
      unit: "кг",
      popular: true,
      desc: "Тепличные и грунтовые томаты собственной селекции. Плотная мякоть, высокая лёжкость, стабильный калибр — под сети и HoReCa.",
      image: "img/photos/tomaty.jpg",
    },
    {
      id: "ogurcy",
      name: "Огурцы",
      category: "ovoshchi",
      categoryName: "Овощи",
      url: "produkciya/ovoshchi/ogurcy.html",
      seo: "огурцы оптом с поля",
      variety: "Кураж, Герман, короткоплодные тепличные",
      caliber: "10–14 см / 14–18 см",
      pack: "ящик 5 кг, сетка 10 кг",
      storage: "+10…+12 °C",
      shelf: "7–10 суток",
      season: "март–ноябрь",
      seasonKeys: ["vesna", "leto", "osen"],
      packKeys: ["yashik", "setka"],
      caliberKeys: ["sredniy"],
      volume: "до 60 т/нед",
      priceKg: 72,
      pricePack: 360,
      priceTon: 65000,
      unit: "кг",
      popular: true,
      desc: "Хрустящие огурцы без горечи. Ежедневный съём, охлаждение на складе в день сбора.",
      image: "img/photos/ogurcy.jpg",
    },
    {
      id: "kartofel",
      name: "Картофель",
      category: "ovoshchi",
      categoryName: "Овощи",
      url: "produkciya/ovoshchi/kartofel.html",
      seo: "картофель оптом Краснодар",
      variety: "Гала, Ред Скарлет, Коломба",
      caliber: "35–55 мм / 55–75 мм",
      pack: "сетка 25 кг, биг-бэг 500 кг",
      storage: "+4…+6 °C",
      shelf: "до 6 месяцев (склад)",
      season: "июль–апрель",
      seasonKeys: ["leto", "osen", "zima", "vesna"],
      packKeys: ["setka", "bigbag"],
      caliberKeys: ["sredniy", "krupnyy"],
      volume: "до 400 т/нед",
      priceKg: 28,
      pricePack: 700,
      priceTon: 25000,
      unit: "кг",
      popular: true,
      desc: "Продовольственный картофель с собственных полей. Мойка и калибровка под заказ сети.",
      image: "img/photos/kartofel.jpg",
    },
    {
      id: "morkov",
      name: "Морковь",
      category: "ovoshchi",
      categoryName: "Овощи",
      url: "produkciya/ovoshchi/morkov.html",
      seo: "морковь оптом",
      variety: "Нантская, Каскад F1",
      caliber: "18–25 мм / 25–40 мм",
      pack: "мешок 10 кг, ящик 15 кг",
      storage: "0…+2 °C",
      shelf: "до 4 месяцев",
      season: "июнь–март",
      seasonKeys: ["leto", "osen", "zima"],
      packKeys: ["meshok", "yashik"],
      caliberKeys: ["sredniy"],
      volume: "до 90 т/нед",
      priceKg: 34,
      pricePack: 340,
      priceTon: 31000,
      unit: "кг",
      popular: true,
      desc: "Сладкая морковь насыщенного цвета. Мытая и немытая, фасовка под розницу и общепит.",
      image: "img/photos/morkov.jpg",
    },
    {
      id: "svekla",
      name: "Свёкла",
      category: "ovoshchi",
      categoryName: "Овощи",
      url: "produkciya/ovoshchi/svekla.html",
      seo: "свёкла оптом",
      variety: "Бордо 237, Пабло F1",
      caliber: "60–80 мм / 80–120 мм",
      pack: "сетка 20 кг",
      storage: "0…+2 °C",
      shelf: "до 5 месяцев",
      season: "август–апрель",
      seasonKeys: ["leto", "osen", "zima", "vesna"],
      packKeys: ["setka"],
      caliberKeys: ["sredniy", "krupnyy"],
      volume: "до 50 т/нед",
      priceKg: 26,
      pricePack: 520,
      priceTon: 24000,
      unit: "кг",
      popular: false,
      desc: "Столовая свёкла ровной формы, без round-дефектов. Подходит для переработки и розницы.",
      image: "img/photos/svekla.jpg",
    },
    {
      id: "kapusta",
      name: "Капуста белокочанная",
      category: "ovoshchi",
      categoryName: "Овощи",
      url: "produkciya/ovoshchi/kapusta.html",
      seo: "капуста оптом",
      variety: "Агрессор, Ринда",
      caliber: "1,5–2,5 кг / 2,5–4 кг",
      pack: "сетка 20 кг, паллета",
      storage: "0…+1 °C",
      shelf: "до 6 месяцев",
      season: "июнь–март",
      seasonKeys: ["leto", "osen", "zima"],
      packKeys: ["setka"],
      caliberKeys: ["sredniy", "krupnyy"],
      volume: "до 120 т/нед",
      priceKg: 22,
      pricePack: 440,
      priceTon: 20000,
      unit: "кг",
      popular: false,
      desc: "Плотные кочаны для хранения и свежего рынка. Ранняя и поздняя группы спелости.",
      image: "img/photos/kapusta.jpg",
    },
    {
      id: "luk",
      name: "Лук репчатый",
      category: "ovoshchi",
      categoryName: "Овощи",
      url: "produkciya/ovoshchi/luk.html",
      seo: "лук оптом",
      variety: "Стурон, Ред Барон",
      caliber: "50–70 мм / 70–90 мм",
      pack: "сетка 25 кг",
      storage: "0…+4 °C",
      shelf: "до 8 месяцев",
      season: "июль–май",
      seasonKeys: ["leto", "osen", "zima", "vesna"],
      packKeys: ["setka"],
      caliberKeys: ["sredniy", "krupnyy"],
      volume: "до 150 т/нед",
      priceKg: 31,
      pricePack: 775,
      priceTon: 28000,
      unit: "кг",
      popular: false,
      desc: "Жёлтый и красный лук. Сушка, сортировка, стабильная шелуха для дальних перевозок.",
      image: "img/photos/luk.jpg",
    },
    {
      id: "perec",
      name: "Перец сладкий",
      category: "ovoshchi",
      categoryName: "Овощи",
      url: "produkciya/ovoshchi/perec.html",
      seo: "перец болгарский оптом",
      variety: "классика красный/жёлтый/зелёный",
      caliber: "80–120 г / 150–200 г",
      pack: "гофрокороб 5 кг",
      storage: "+7…+10 °C",
      shelf: "10–12 суток",
      season: "июнь–октябрь",
      seasonKeys: ["leto", "osen"],
      packKeys: ["gofra"],
      caliberKeys: ["sredniy", "krupnyy"],
      volume: "до 35 т/нед",
      priceKg: 118,
      pricePack: 590,
      priceTon: 108000,
      unit: "кг",
      popular: true,
      desc: "Толстостенный перец для сетей и кулинарии. Сортировка по цвету и калибру.",
      image: "img/photos/perec.jpg",
    },
    {
      id: "yabloki",
      name: "Яблоки",
      category: "frukty",
      categoryName: "Фрукты",
      url: "produkciya/frukty/yabloki.html",
      seo: "яблоки оптом с поля",
      variety: "Гала, Голден, Айдаред, Фуджи",
      caliber: "65–75 мм / 75–85 мм",
      pack: "гофрокороб 12 кг, лоток",
      storage: "+1…+3 °C, РГС",
      shelf: "до 8 месяцев (РГС)",
      season: "август–май",
      seasonKeys: ["leto", "osen", "zima", "vesna"],
      packKeys: ["gofra", "lotok"],
      caliberKeys: ["sredniy", "krupnyy"],
      volume: "до 200 т/нед",
      priceKg: 64,
      pricePack: 768,
      priceTon: 58000,
      unit: "кг",
      popular: true,
      desc: "Сад в предгорьях Кубани. Сортировка по цвету, воск по запросу, отгрузка из холодильника.",
      image: "img/photos/yabloki.jpg",
    },
    {
      id: "grushi",
      name: "Груши",
      category: "frukty",
      categoryName: "Фрукты",
      url: "produkciya/frukty/grushi.html",
      seo: "груши оптом",
      variety: "Конференция, Вильямс",
      caliber: "60–70 мм / 70–80 мм",
      pack: "гофрокороб 10 кг",
      storage: "0…+1 °C",
      shelf: "до 4 месяцев",
      season: "август–январь",
      seasonKeys: ["leto", "osen", "zima"],
      packKeys: ["gofra"],
      caliberKeys: ["sredniy"],
      volume: "до 40 т/нед",
      priceKg: 92,
      pricePack: 920,
      priceTon: 85000,
      unit: "кг",
      popular: false,
      desc: "Сочные груши ручного съёма. Дозаривание под график клиента.",
      image: "img/photos/grushi.jpg",
    },
    {
      id: "slivy",
      name: "Сливы",
      category: "frukty",
      categoryName: "Фрукты",
      url: "produkciya/frukty/slivy.html",
      seo: "слива оптом",
      variety: "Стенли, Президент",
      caliber: "35–45 мм",
      pack: "ящик 6 кг",
      storage: "0…+2 °C",
      shelf: "14–21 сутки",
      season: "июль–сентябрь",
      seasonKeys: ["leto", "osen"],
      packKeys: ["yashik"],
      caliberKeys: ["sredniy"],
      volume: "до 25 т/нед",
      priceKg: 78,
      pricePack: 468,
      priceTon: 72000,
      unit: "кг",
      popular: false,
      desc: "Плотная слива для свежего рынка и переработки. Сбор в технической и потребительской зрелости.",
      image: "img/photos/slivy.jpg",
    },
    {
      id: "klubnika",
      name: "Клубника",
      category: "yagody",
      categoryName: "Ягоды",
      url: "produkciya/yagody/klubnika.html",
      seo: "клубника оптом",
      variety: "Альба, Клери, ремонтант",
      caliber: "18–25 мм / 25+ мм",
      pack: "лоток 250/500 г, ящик 2 кг",
      storage: "0…+2 °C",
      shelf: "3–5 суток",
      season: "май–октябрь",
      seasonKeys: ["vesna", "leto", "osen"],
      packKeys: ["lotok", "yashik"],
      caliberKeys: ["sredniy", "krupnyy"],
      volume: "до 12 т/нед",
      priceKg: 280,
      pricePack: 140,
      priceTon: 260000,
      unit: "кг",
      popular: false,
      desc: "Ягода утреннего сбора, охлаждение в течение 2 часов. Для ритейла и кондитерских.",
      image: "img/photos/klubnika.jpg",
    },
    {
      id: "malina",
      name: "Малина",
      category: "yagody",
      categoryName: "Ягоды",
      url: "produkciya/yagody/malina.html",
      seo: "малина оптом",
      variety: "Полка, Glen Ample",
      caliber: "стандарт / экстра",
      pack: "лоток 125/250 г",
      storage: "0…+2 °C",
      shelf: "2–4 суток",
      season: "июнь–сентябрь",
      seasonKeys: ["leto", "osen"],
      packKeys: ["lotok"],
      caliberKeys: ["sredniy"],
      volume: "до 4 т/нед",
      priceKg: 420,
      pricePack: 105,
      priceTon: 390000,
      unit: "кг",
      popular: false,
      desc: "Целая ягода без рассыпания. Отгрузка ночными рейсами в Центральный округ.",
      image: "img/photos/malina.jpg",
    },
    {
      id: "ukrop",
      name: "Укроп",
      category: "zelen",
      categoryName: "Зелень",
      url: "produkciya/zelen/ukrop.html",
      seo: "укроп оптом",
      variety: "Аллигатор, Грибовский",
      caliber: "пучок 50/100 г",
      pack: "ящик 3 кг, вакуум по запросу",
      storage: "+2…+4 °C",
      shelf: "5–7 суток",
      season: "круглый год",
      seasonKeys: ["zima", "vesna", "leto", "osen"],
      packKeys: ["yashik", "vakuum"],
      caliberKeys: ["sredniy"],
      volume: "до 8 т/нед",
      priceKg: 95,
      pricePack: 285,
      priceTon: 88000,
      unit: "кг",
      popular: false,
      desc: "Свежая зелень с гидропонных линий и открытого грунта. Ежедневные отгрузки.",
      image: "img/photos/ukrop.jpg",
    },
    {
      id: "petrushka",
      name: "Петрушка",
      category: "zelen",
      categoryName: "Зелень",
      url: "produkciya/zelen/petrushka.html",
      seo: "петрушка оптом",
      variety: "листовая, кудрявая",
      caliber: "пучок 50/100 г",
      pack: "ящик 3 кг",
      storage: "+2…+4 °C",
      shelf: "5–7 суток",
      season: "круглый год",
      seasonKeys: ["zima", "vesna", "leto", "osen"],
      packKeys: ["yashik"],
      caliberKeys: ["sredniy"],
      volume: "до 6 т/нед",
      priceKg: 110,
      pricePack: 330,
      priceTon: 102000,
      unit: "кг",
      popular: false,
      desc: "Насыщенный цвет и аромат. Фасовка для кулинарии и розничных сетей.",
      image: "img/photos/petrushka.jpg",
    },
    {
      id: "salat",
      name: "Салат",
      category: "zelen",
      categoryName: "Зелень",
      url: "produkciya/zelen/salat.html",
      seo: "салат оптом",
      variety: "айсберг, романо, лолло росса",
      caliber: "голова 300–500 г",
      pack: "гофрокороб 4 кг, плёнка",
      storage: "+1…+3 °C",
      shelf: "7–10 суток",
      season: "круглый год",
      seasonKeys: ["zima", "vesna", "leto", "osen"],
      packKeys: ["gofra", "plenka"],
      caliberKeys: ["sredniy"],
      volume: "до 15 т/нед",
      priceKg: 145,
      pricePack: 580,
      priceTon: 135000,
      unit: "кг",
      popular: false,
      desc: "Хрустящие салаты из теплиц. Промывка и охлаждение перед упаковкой.",
      image: "img/photos/salat.jpg",
    },
    {
      id: "luk-zelenyj",
      name: "Лук зелёный",
      category: "zelen",
      categoryName: "Зелень",
      url: "produkciya/zelen/luk-zelenyj.html",
      seo: "лук зелёный оптом",
      variety: "перо 25–40 см",
      caliber: "пучок 100 г",
      pack: "ящик 4 кг, вакуум",
      storage: "+1…+3 °C",
      shelf: "6–8 суток",
      season: "круглый год",
      seasonKeys: ["zima", "vesna", "leto", "osen"],
      packKeys: ["yashik", "vakuum"],
      caliberKeys: ["sredniy"],
      volume: "до 10 т/нед",
      priceKg: 86,
      pricePack: 344,
      priceTon: 79000,
      unit: "кг",
      popular: false,
      desc: "Ровное перо, белая ножка. Подходит для сетей и HoReCa, вакуумная упаковка по запросу.",
      image: "img/photos/luk-zelenyj.jpg",
    },
  ],
  news: [
    {
      id: "sborn-yablok-2026",
      date: "18.09.2026",
      title: "Старт сбора яблок: Гала и Голден",
      excerpt: "Открыли сезон яблок ранних сортов. Объёмы до 200 тонн в неделю, сортировка 65–85 мм.",
      image: "img/photos/garden.jpg",
    },
    {
      id: "novye-teplicy",
      date: "02.09.2026",
      title: "Запустили ещё 4 га зимних теплиц",
      excerpt: "Расширили мощности под томат и зелень — круглогодичные поставки без просадок объёма.",
      image: "img/photos/greenhouse.jpg",
    },
    {
      id: "ceny-oktyabr",
      date: "01.10.2026",
      title: "Обновление прайса на октябрь",
      excerpt: "Скорректировали оптовые цены на томат, перец и морковь. Актуальная таблица — в разделе «Цены».",
      image: "img/photos/harvest.jpg",
    },
    {
      id: "logistika-cfo",
      date: "12.08.2026",
      title: "Свой рейс в Центральный округ дважды в неделю",
      excerpt: "Добавили регулярную фуру Краснодар — Москва / Тула / Воронеж. Срок 24–36 часов.",
      image: "img/photos/logistics.jpg",
    },
  ],
  categories: [
    { id: "ovoshchi", name: "Овощи", url: "produkciya/ovoshchi/", image: "img/photos/ovoshchi.jpg" },
    { id: "frukty", name: "Фрукты", url: "produkciya/frukty/", image: "img/photos/frukty.jpg" },
    { id: "yagody", name: "Ягоды", url: "produkciya/yagody/", image: "img/photos/yagody.jpg" },
    { id: "zelen", name: "Зелень", url: "produkciya/zelen/", image: "img/photos/zelen.jpg" },
  ],
};

window.GREENECO.PRICE_KEY = "greeneco_prices_v1";
window.GREENECO.DATE_KEY = "greeneco_price_date";

window.GREENECO.getPrices = function () {
  try {
    const raw = localStorage.getItem(window.GREENECO.PRICE_KEY);
    if (!raw) return null;
    return JSON.parse(raw);
  } catch (e) {
    return null;
  }
};

window.GREENECO.applyPrices = function (products) {
  const overlay = window.GREENECO.getPrices();
  if (!overlay) return products;
  return products.map(function (p) {
    const o = overlay[p.id];
    if (!o) return p;
    return Object.assign({}, p, {
      priceKg: o.priceKg != null ? o.priceKg : p.priceKg,
      pricePack: o.pricePack != null ? o.pricePack : p.pricePack,
      priceTon: o.priceTon != null ? o.priceTon : p.priceTon,
      volume: o.volume || p.volume,
    });
  });
};

window.GREENECO.priceDate = function () {
  return localStorage.getItem(window.GREENECO.DATE_KEY) || window.GREENECO.company.priceUpdated;
};
